apiVersion: apps/v1
kind: Deployment
metadata:
  name: analytics-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: analytics
  template:
    metadata:
      labels:
        app: analytics
    spec:
      containers:
        - name: analytics
          image: nipundew/lugx-analytics:latest
          imagePullPolicy: Always
          ports:
            - containerPort: 8080
          env:
            - name: CLICKHOUSE_ENDPOINT
              valueFrom:
                secretKeyRef:
                  name: lugx-secret
                  key: CLICKHOUSE_ENDPOINT
            - name: CLICKHOUSE_USERNAME
              valueFrom:
                secretKeyRef:
                  name: lugx-secret
                  key: CLICKHOUSE_USERNAME
            - name: CLICKHOUSE_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: lugx-secret
                  key: CLICKHOUSE_PASSWORD
