apiVersion: apps/v1
kind: Deployment
metadata:
  name: games-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: games
  template:
    metadata:
      labels:
        app: games
    spec:
      containers:
        - name: games
          image: nipundew/lugx-games:latest
          imagePullPolicy: Always
          ports:
            - containerPort: 8080
          env:
            - name: DB_URL
              valueFrom:
                secretKeyRef:
                  name: lugx-secret
                  key: GAMES_DB_URL
            - name: DB_USERNAME
              valueFrom:
                secretKeyRef:
                  name: lugx-secret
                  key: DB_USERNAME
            - name: DB_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: lugx-secret
                  key: DB_PASSWORD
