apiVersion: apps/v1
kind: Deployment
metadata:
  name: clickhouse-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: clickhouse
  template:
    metadata:
      labels:
        app: clickhouse
    spec:
      containers:
        - name: clickhouse
          image: nipundew/lugx-analytics-clickhouse:latest
          imagePullPolicy: Always
          ports:
            - containerPort: 8123
            - containerPort: 9000
            - containerPort: 9009
          env:
            - name: CLICKHOUSE_USER
              value: "default"
            - name: CLICKHOUSE_PASSWORD
              value: "test123"
