name: Deploy to Kubernetes

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      # Step1: Checkout the code
      - name: Checkout code
        uses: actions/checkout@v4

        # Step2: Apply the Kubernetes configurations
      - name: Deploy to EC2 via SSH
        uses: appleboy/ssh-action@v1.2.0
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ${{ secrets.EC2_USER }}
          key: ${{ secrets.EC2_SSH_KEY }}
          script: |
            # Navigate to the project directory
            cd /home/ec2-user/Kube-Test-K8s || exit 1
            
            # Pull latest changes from git
            git pull origin master
            
            # Apply Kubernetes configurations
            kubectl apply -f kube-configs/deployment-*.yml
            kubectl apply -f kube-configs/service-*.yml
            kubectl apply -f kube-configs/lugx-ingress.yml
            
            # Check deployment status
            kubectl get deployments
            kubectl get services
            kubectl get ingress
